name: mana_icons_flutter
description: "Magic: The Gathering symbols as icons in a flutter application."
version: 0.0.1
homepage: https://github.com/j7126/mana_icons_flutter

environment:
  sdk: '>=3.2.3 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  fonts:
    - family: mana
      fonts:
       - asset: fonts/mana.ttf
